config/routes.rb
Rails.application.routes.draw do
  get 'browses/show'

  get 'upload_inspect_informations/upload'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'static_pages#home'
  post '/store_log', to: 'static_pages#store_log'

  get  '/upload', to: 'upload_inspect_informations#upload'
  post '/upload', to: 'upload_inspect_informations#store_and_analysis'

  resources :browses, only: [:show] do
    collection do
      get :index
      post :compare
      post :download_excel
      post :download_summary
    end

    member do
      get :history
    end
  end

end

app/controllers/browses_controller.rb
class BrowsesController < ApplicationController

  # you can disable csrf protection on controller-by-controller basis:  
  protect_from_forgery except: :index 
  skip_before_action :verify_authenticity_token  

  def show
    return redirect_to browses_path if params[:id] == 'compare'
    @sf = StoreFile.find(params[:id])
    
    @device_manager = aio_parse_console(@sf.path)
  end

  def index
    @store_files = StoreFile.paginate(page: params[:page])
    @cl_group = StoreFile.client_and_location_group
  end

  def history
    @sf = StoreFile.find(params[:id])

    @history_arr = @sf.history
  end

  def compare
    compare_one = params['key1'].split('client-')[1]
    compare_two = params['key2'].split('client-')[1]
    return if compare_one.nil? or compare_two.nil?

    sf_one = StoreFile.find_by_id(compare_one)
    sf_two = StoreFile.find_by_id(compare_two)

    @device_manager = aio_parse_compare(sf_one.path, sf_two.path)
  end

  def download_excel
    @sf = StoreFile.find(params[:id])

    # 生成excel临时文件
    tmp_file = aio_parse_to_wps_excel(@sf.path, random_temp_path)
    return if tmp_file.nil?
    send_file(tmp_file, filename: "#{@sf.slug + '.xls'}")
  end

  def download_summary
    @sf = StoreFile.find(params[:id])

    # 生成summary临时文件
    tmp_file = aio_parse_to_summary(@sf.path, random_temp_path)
    return if tmp_file.nil?
    send_file(tmp_file, filename: "#{@sf.slug + '.doc'}")
  end
end

app/helpers/browses_helper.rb
module BrowsesHelper
end

app/views/browses/_client_nav.html.slim
nav.nav
  ul
    li

app/views/browses/_device_table.html.slim
fieldset
  table.table.table-striped.table-hover
    tr
      th.th-down #{" "}
      th.th-status 状态
      th 设备名称
      th 设备型号

    - @device_manager.each_devices do |name, klass|
      tr 
        td
          a data-toggle='collapse' href='##{name}'
            span.glyphicon.glyphicon-collapse-down

        / 判断故障性质
        - ws = @device_manager.warning_summarize
        - if ws.has_serious?
          td 严重
        - elsif ws.has_ordinary?
          td 中度
        - else
          td 正常

        td #{name}
        td #{klass.device_type.upcase}

      tr.panel-collapse.collapse id="#{name}"
        td 
        td colspan='3'
          ul 
            li
              label Version
              span<> #{klass.ios_version}

            li
              label run time
              span<> #{klass.uptime}

            li
              label CPU(%)
              span<> #{klass.cpu_percent.to_s + "%"}

            li
              label MEMORY(%)
              span<> #{klass.memory_percent.to_s + "%"}

app/views/browses/_download_excel_and_summary.slim
div.row
  / LEARN button_to
  = button_to '下载 Excel 巡检报告', action: 'download_excel', params: { id: @sf } 
  = button_to '下载 Word 巡检简报', action: 'download_summary', params: { id: @sf }

app/views/browses/_total_info.html.slim
ul.list-group
  li.list-group-item.active
    label 概况

  li.list-group-item
    label 设备数量
    span<> = @device_manager.devices_number

app/views/browses/compare.html.slim
- provide(:title, '比较')

- @device_manager.each_devices do |name, klass|
  fieldset.compare
    div
      p #{name}
      - klass.warning_info_compare.each_cmd_with_diff do |cmd, diff|
        p #{cmd}

        / 获取本命令的差异值
        table
          colgroup
            col width='40'
            col
            col width='40'
            col

            - aio_print(diff).each do |text|
              - cm1 = text.first
              - cm2 = text.last

              tr
                td [ class="#{cm1.type.to_s + '_style_con'} blob-num" ] = cm1.old_number
                td [ class="#{cm1.type.to_s + '_style'}" ] = cm1.text
                td [ class="#{cm2.type.to_s + '_style_con'} blob-num" ] = cm2.new_number
                td [ class="#{cm2.type.to_s + '_style'}" ] = cm2.text

app/views/browses/history.html.slim
- provide(:title, '历史版本')

- title = "#{@sf.client.name} #{@sf.client.city.name} #{@sf.inspect_time}"

h1 = title

div.row
  div.col-md-8.col-md-offset-2
    table.table.table-striped.table-hover
      tr
        th.th-status 版本
        th 台数
        th 操作

      - @history_arr.each_with_index do |sf, n|

        tr
          td = n + 1
          td = sf.devices_number
          td = link_to '查看', browse_path(sf)

app/views/browses/index.html.slim
- provide(:title, '地市巡检记录')
h1 地市巡检记录

div.row
  div.col-md-2
    = render 'client_nav'

  div.col-md-8
    table.table.table-striped.table-hover
      
      tr
        th.th-down #{' '}
        th 客户
        th 所在地
        th 巡检时间
        th 上传时间
        th 操作

      - @store_files.each do |sf|
        - next unless sf.recently

        tr
          td 
            input type='checkbox' name="client-#{sf.id}" value="client-#{sf.id}"
          td = sf.client.name
          td = sf.client.city.name
          td = sf.inspect_time
          td = sf.created_at
          td 
            = link_to '转到', browse_path(sf)
            = " / "
            = link_to '历史', history_browse_path(sf)

  div.col-md-2
    input.btn.btn-lg.btn-success#compareBtn type='button' value='比较'

javascript:
  document.getElementById('compareBtn').onclick=function() {
    var x = document.getElementsByTagName('input');
    var boxes = new Array(2);
    var index = 0;

    for(var i=0; i < x.length; i++){
      if (x[i].type == 'checkbox') {
        if(x[i].checked){
          boxes[index] = x[i];
          index = index + 1;
        }
      }
    }

    // 发送post
    doFormRequest('#{compare_browses_url}', 'post', {'key1':boxes[0].value, 'key2':boxes[1].value});
  }


javascript:
  /*
  * @url: url link
  * @action: "get", "post"
  * @json: {'key1':'value2', 'key2':'value2'}
  */
  function doFormRequest(url, action, json)
  {
      var form = document.createElement("form");
      form.action = url;
      form.method = action;
      // append input attribute and valus
      for (var key in json)
      {
        if (json.hasOwnProperty(key))
        {
          var val = json[key];
          input = document.createElement("input");
          input.type = "hidden";
          input.name = key;
          input.value = val;
          // append key-value to form
          form.appendChild(input)
        }
      }
      // send post request
      document.body.appendChild(form);
      form.submit();
      // remove form from document
      document.body.removeChild(form);
  }

javascript:
  $(document).ready(function() {
  $('input[type=checkbox]').click(function(e) {
    if ($("input[type='checkbox']:checked").length > 2) {
      e.preventDefault();
      alert("最多选择2个");
   }
  });
 })

app/views/browses/show.html.slim
- title = "#{@sf.client.name} #{@sf.client.city.name} #{@sf.inspect_time} 巡检"
- provide(:title, title)

div#show-inspect

  h1 #{title}

  div.row

    div.col-md-3
      = render 'download_excel_and_summary'
      = render 'total_info'

    div.col-md-9
      = render 'device_table'