config/routes.rb
Rails.application.routes.draw do
  get 'browses/show'

  get 'upload_inspect_informations/upload'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'static_pages#home'
  post '/store_log', to: 'static_pages#store_log'

  get  '/upload', to: 'upload_inspect_informations#upload'
  post '/upload', to: 'upload_inspect_informations#store_and_analysis'

  resources :browses, only: [:show] do
    collection do
      get :index
      post :compare
      post :download_excel
      post :download_summary
    end

    member do
      get :history
    end
  end

end

app/views/layouts/_footer.html.slim
h5 This is footer

app/views/layouts/_header.html.slim
header
  div.site-title
    h1 = link_to 'Inspect Manager Center', root_path

    ul.header-item.tabs#tabs
      li = link_to '所有地市', browses_path

    ul.header-item.tabs#utility_nav
      li = link_to current_user.email, '#'
      li = link_to '注销', destroy_user_session_path, method: :delete
  

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

  / 对登录的单独进行处理
  - if login_path?
    body.login
      div#wrapper
        div#content-wrapper
          - flash.each do |msg_type, msg|
            = content_tag(:div, msg, class: "alert alert-#{msg_type}")
          = yield

  - else
    body  
      div.wrapper
        = render 'layouts/header'

        - flash.each do |msg_type, msg|
          = content_tag(:div, msg, class: "alert alert-#{msg_type}")


        div.main-body
          = yield

        = render 'layouts/footer'

        div.row
          = debug(params) if Rails.env.development?